# Generated by Django 2.0.2 on 2018-02-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='before_spoiler',
            field=models.TextField(default='None'),
        ),
    ]
