# Generated by Django 2.0.2 on 2018-03-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_before_spoiler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='post_text',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_comments', to='blog_app.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='before_spoiler',
            field=models.TextField(default='The post do not have a brief description.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=254),
        ),
    ]
